#!/bin/bash
#===============================================================================
# vim: softtabstop=4 shiftwidth=4 expandtab fenc=utf-8 spell spelllang=en cc=81
#===============================================================================

# ---------------------------------------------------------------------------- #
# Copyright 2013, databus.pro                                                  #
# Author: Valentin Bud                                                         #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

# ------------------------------------------------------------------------------ 
# Arguments
# ------------------------------------------------------------------------------ 

DEPLOY_ID=$3

# ------------------------------------------------------------------------------ 
# Destroy the LXC Container
# ------------------------------------------------------------------------------ 

function destroy_container 
{
    sudo lxc-stop -n one-${DEPLOY_ID}
    rm -rf ${LXC_DIRECTORY}/one-${DEPLOY_ID}
}

exec_and_log destroy_container \
    "Could not destroy ${DEPLOY_ID}"
